### ISSUE TITLE
Browser access mode in the Prometheus datasource is no longer available. Switch to server access mode.

### ISSUE THREAD

**Issue by deadcode0815** [utkuozdemir/nvidia_gpu_exporter#114]
I did run (admin mode) https://raw.githubusercontent.com/utkuozdemir/nvidia_gpu_exporter/master/install/windows.ps1
After importing the dashboard I get the following error message (grafana):
Browser access mode in the Prometheus datasource is no longer available. Switch to server access mode.

Prometheus did drop support for Browser access mode (related!? https://github.com/grafana/grafana/issues/43859)

**Comment by utkuozdemir** [comment]
Thanks, good catch. Can you try to change `access: direct` to `access: proxy` in the powershell script and try again?

From the first look of it, the script seems pretty broken on Windows 11.

**Comment by deadcode0815** [comment]
I did change access: direct to access: proxy - dashboard looks good now. I'm btw running win11, had no issues running the script

**Comment by utkuozdemir** [comment]
@deadcode0815 Good to hear, I'll do the changes.

When I tested quickly, I had some issues with scoop complaining about running as admin 🤔
