### ISSUE TITLE
Add instance filter in Grafana dashboard

### ISSUE THREAD

**Issue by dennys** [utkuozdemir/nvidia_gpu_exporter#129]
**Is your feature request related to a problem? Please describe.**
When I have several machines, it's not easy to find the correct GPU by UUID.
Therefore, I try to add an _instance_ filter in dashboard.

**Describe the solution you'd like**
The following is my procedures, plesae consider to add it, thanks.

First, add a new Grafana dashboard variable

1. Settings -> variables
2. Click \+ New variable
3. Assign the name (I use 'instance') and label (I use 'Instance')
4. Change 'query types' to 'label values'
5. Select 'instance' in 'Label' field
6. Input '\d+\.\d+\.\d+\.\d+:9835' in Regex (I use default port 9835)
7. Press Apply and you have a new variable in your dashboard now.

Second, modify the GPU variable

1. Settings -> variables
2. Click 'gpu'
3. Modify 'label filters', I use 'instance' = '$instance'
4. Press Apply

And you can switch the order of the 2 variables to be more intuitive.

After saving the settings, you have 2 variables in dashboard.
And when you change 'instance', the 'gpu' list should be changed.

I think the Regex is not a good idea, but if I don't add it, it shows all other instances like Node exporter, ...
Please let me know if there is a better solution, thanks.

**Comment by vennelakanti2511** [comment]
Hi Dennys
I've a similar requirement and I see this as a great solution to have two variables so that only when a particular host is selected, only the corresponding GPUs can be selected from the second variable.

Unfortunately, I do not see the option to modify the filter to add  'instance' = '$instance'. 
Please check the screenshot below and suggest. Would be really helpful.

**Comment by vennelakanti2511** [comment]
![IMG_0156](https://github.com/utkuozdemir/nvidia_gpu_exporter/assets/140266627/085ad408-79e3-4e70-9f78-aba6888dad80)

**Comment by dennys** [comment]
@vennelakanti2511 This is the screen shot of  Grafana 10.4. I'm not sure is it changed in Grafana 11.
![image](https://github.com/utkuozdemir/nvidia_gpu_exporter/assets/86308/aa9997c7-75b9-4568-a29c-5f771b304f0f)

**Comment by anh193** [comment]
Dennys, thanks for the great workaround! There yet has come another question, how do I bind the IP addresses of the instances to some certain custom hostnames? Do you have any idea?

**Comment by dennys** [comment]
> Dennys, thanks for the great workaround! There yet has come another question, how do I bind the IP addresses of the instances to some certain custom hostnames? Do you have any idea?

I don't see hostname in the output of this exporter, maybe need to issue another feature request.

**Comment by anh193** [comment]
> > Dennys, thanks for the great workaround! There yet has come another question, how do I bind the IP addresses of the instances to some certain custom hostnames? Do you have any idea?
> 
> I don't see hostname in the output of this exporter, maybe need to issue another feature request.

okay. How about binding the IPs to some manually set names as like variables.?

**Comment by zhan9san** [comment]
@dennys @vennelakanti2511 @anh193 

I tested the change in #221 in my own Grafana, and it works like a charm.

Would you like have a try?

**Comment by dennys** [comment]
> @dennys @vennelakanti2511 @anh193
> 
> I tested the change in #221 in my own Grafana, and it works like a charm.
> 
> Would you like have a try?

It works for me, cool, thanks.
