### ISSUE TITLE
Can't figure out how to connect to Grafana cloud

### ISSUE THREAD

**Issue by bluecanarybe** [utkuozdemir/nvidia_gpu_exporter#131]
Hi,

I have it working locally on my linux machine and the localhost metrics page works. But I have no idea on how to send those events to Grafana cloud.

**Comment by utkuozdemir** [comment]
I haven't used Grafana Cloud, but it seems you need to use remote_write option of Prometheus to push its metrics into cloud. You anyway need a Prometheus somewhere to scrape the metrics from the exporter endpoint, direct connection to Grafana is not possible.

**Comment by bluecanarybe** [comment]
That worked!

**Comment by Elfsong** [comment]
> That worked!

May I ask how to do that? Thanks!
