### ISSUE TITLE
macOS binaries?

### ISSUE THREAD

**Issue by johnnynunez** [utkuozdemir/nvidia_gpu_exporter#137]
Macos binaries for M1/M2/M3?
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

**Comment by utkuozdemir** [comment]
I can definitely add darwin/arm64 to the builds, but I'm curious - are you running the exporter on Mac? There's [a way to scrape metrics remotely](https://github.com/utkuozdemir/nvidia_gpu_exporter/blob/master/CONFIGURE.md#remote-scraping-configuration), but I had the impression that it is very rarely used that way, if at all.
