### ISSUE TITLE
how to add Total RAM , GPU Core, CUDA Core, CPU Core, and RAM in used etc

### ISSUE THREAD

**Issue by souravsk** [utkuozdemir/nvidia_gpu_exporter#173]
The node exporter given by Prometheus has Total RAM, CPU, and all the other metrics data.

How to add to my Grafana dashboard

**Comment by md-carlpickering** [comment]
> The node exporter given by Prometheus has Total RAM, CPU, and all the other metrics data.
> 
> How to add to my Grafana dashboard



> The node exporter given by Prometheus has Total RAM, CPU, and all the other metrics data.
> 
> How to add to my Grafana dashboard

I don't understand your question. Do you mean to ask, once you have installed the nvidia_gpu_exporter, how do you get it within Grafana? If so, you'll see within the folder grafana, a JSON file, which should be imported within Grafana > Dashboards > Browse > Import, then paste or upload the JSON

**Comment by utkuozdemir** [comment]
As I understand, @souravsk wants to show the data coming from node_exporter and data from this exporter in a single dashboard.

I suggest using node_exporter's own dashboard and this exporter's own dashboard separately. If you really want a single dashboard, you have the sources available, so you can edit/create a new dashboard.

In any case, it is out of scope of this project.
