### ISSUE TITLE
Add sponsorship abiltiy / buymeacoffee

### ISSUE THREAD

**Issue by oregonpillow** [utkuozdemir/nvidia_gpu_exporter#199]
Love the project, would like to support by making a donation. Can you please enabling GitHub sponsorship or similar?

Thanks.

**Comment by utkuozdemir** [comment]
Thank you very much for your thoughtfulness. You made my day :)

I find barely any time to maintain my projects, so I don't plan to enable any sponsorship. Please consider donating that amount to a charity of your choice instead (maybe one of the effective ones, like the ones on GiveWell...).

Thanks again!

**Comment by oregonpillow** [comment]
Done. To the The Malaria Consortium, good idea with GiveWell :) And you're welcome, thanks for making the exporter :)

**Comment by oregonpillow** [comment]
I referenced your project in my blog: https://oregonpillow.com/blog/grafana-gaming/

**Comment by utkuozdemir** [comment]
Nice post, and great looking blog! Thank you.
