### ISSUE TITLE
The dashboard and the exporter use completely different metic-names?

### ISSUE THREAD

**Issue by sorenwacker** [utkuozdemir/nvidia_gpu_exporter#245]
When I use the exporter like this

```
BootStrap: docker
From: utkuozdemir/nvidia_gpu_exporter:1.1.0

%environment
    export NVIDIA_VISIBLE_DEVICES=all

%post
    # Ensure necessary permissions are set
    chmod +x /usr/bin/nvidia_gpu_exporter

%startscript
    exec /usr/bin/nvidia_gpu_exporter
 ```
 
 together with the dashboard:
 
 https://grafana.com/grafana/dashboards/19172-nvidia-gpu-metrics/
 
 I get:
 
 
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/70ef71e2-5f6a-4cc4-a70b-1857da2b3d35">

It seems there is a mismatch between the exported metrics and the ones expected by the dashboard.

**Comment by utkuozdemir** [comment]
This looks more like there's an issue with the data source, as none of the metrics are populated. Can you check the service logs?

Also pls try to hit the exporter's metrics endpoint in your browser (`http://<host>:9835/metrics`) and see two things:
- what it returns
- what it logs

you can post them here, they can be helpful.

**Comment by utkuozdemir** [comment]
Another possibility is, `nvidia-smi` binary not working in the container for some reason. If you find out that is the case (let's say from the logs), you can execute a shell in the container, try to run `nvidia-smi` manually to debug.

**Comment by nhyphamnt** [comment]
Hi @utkuozdemir :
I have the same issue with @sorenwacker . The different thing is I setup the exporter as a service running on GPU server. 
When I curled the metrics, did not see full nvdi-smi metrics like the dashboard query. 
Mine is only shown: 
```user:~> cat metrics.txt | grep smi
# HELP nvidia_smi_command_exit_code Exit code of the last scrape command
# TYPE nvidia_smi_command_exit_code gauge
nvidia_smi_command_exit_code 4
# HELP nvidia_smi_failed_scrapes_total Number of failed scrapes
# TYPE nvidia_smi_failed_scrapes_total counter
nvidia_smi_failed_scrapes_total 607325

```
Checking the service using journalcl command, I found warning and error like below
```
Nov 29 16:19:08 gpuserver  nvidia_gpu_exporter[50719]: ts=2024-11-29T05:19:08.465Z caller=exporter.go:184 level=error error="error running command: exit statu> exit status 4: command failed. code: 4 | command: nvidia-smi --query-gpu=encoder.stats.av>.....


```
Please advise. Thank you.

**Comment by utkuozdemir** [comment]
Also, looking at return value 4, it seems it is returned when the user does not have required permissions - see the return value section here on page 7: https://developer.download.nvidia.com/compute/DCGM/docs/nvidia-smi-367.38.pdf

Can you try to run the failed command manually (get it from the log) as the user nvidia-smi is using? You can try to get it working by trying to give that user different permissions.

**Comment by nhyphamnt** [comment]
Many thanks @utkuozdemir. Following your advice, I ran the command manually and found the permission issue. Now I can see all smi* relating metrics. 
Thank you.
