### ISSUE TITLE
Driver version is not displayed

### ISSUE THREAD

**Issue by ArtemAlagizov** [utkuozdemir/nvidia_gpu_exporter#29]
I have a minor issue of driver version not being displayed in the dashboard.

![image](https://user-images.githubusercontent.com/15367507/131972815-3f70778c-51bf-4461-870e-ff797fd3a20c.png)

Prometheus can't get this info also, it seems
![image](https://user-images.githubusercontent.com/15367507/131974639-e6f9f569-700b-4ad7-af95-9c1679d755fa.png)
![image](https://user-images.githubusercontent.com/15367507/131972997-9a00d9f8-944b-44bd-9dfd-e773e8ed55a6.png)

I run a multinode k8s cluster, where i have the nvidia-gpu-exporter Helm chart deployed.
Each node has Ubuntu 18.04 installed.
When i login to a ozdemir-nvidia-gpu-exporter pod, i can fetch driver version easily like that
```bash
root@ozdemir-nvidia-gpu-exporter-d2j74:/# nvidia-smi --query-gpu=driver_version --format=csv
driver_version
460.91.03
```

**Comment by utkuozdemir** [comment]
I think I know the cause. I'll look into it soon.

**Comment by utkuozdemir** [comment]
Please upgrade to GPU exporter version 0.3.0 (included in the chart version 0.3.1) and upgrade the dashboard to the newest revision (rev 8). It should resolve the issue.

The reason was caused by your version string `460.91.03` having 2 dots, hence not being parsed as a floating point number. I instead included it as a label in the metric with string values.

https://github.com/utkuozdemir/nvidia_gpu_exporter/commit/d7a2ee96d524f190fc0e1e96d08afe6ece6c2f55

**Comment by ArtemAlagizov** [comment]
thanks a lot, man, it works!

i updated the chart, modified the grafana dashboard definition and i see the driver version now.

![image](https://user-images.githubusercontent.com/15367507/132175919-f7e53abf-ee98-4698-9963-556fffabdc1e.png)

here's the updated part of my grafana dashboard
```json
...
{
  "datasource": "Prometheus",
  "description": "The version of the installed NVIDIA display driver. This is an alphanumeric string.",
  "fieldConfig": {
    "defaults": {
      "color": {
        "mode": "thresholds"
      },
      "decimals": 2,
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "unit": "none"
    },
    "overrides": []
  },
  "gridPos": {
    "h": 2,
    "w": 3,
    "x": 0,
    "y": 3
  },
  "id": 14,
  "options": {
    "colorMode": "value",
    "graphMode": "none",
    "justifyMode": "auto",
    "orientation": "auto",
    "reduceOptions": {
      "calcs": [
        "last"
      ],
      "fields": "",
      "values": false
    },
    "text": {},
    "textMode": "name"
  },
  "pluginVersion": "8.1.0",
  "targets": [
    {
      "exemplar": true,
      "expr": "nvidia_smi_gpu_info{uuid=\"$gpu\"}",
      "instant": true,
      "interval": "",
      "legendFormat": "{{driver_version}}",
      "refId": "A"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Driver Version",
  "type": "stat"
},
 ...
```

**Comment by utkuozdemir** [comment]
Awesome. Rev 8 of the dashboard I uploaded here contains the same change as well: https://grafana.com/grafana/dashboards/14574/revisions
