### ISSUE TITLE
Question on displaying node name for a multinode setup

### ISSUE THREAD

**Issue by ArtemAlagizov** [utkuozdemir/nvidia_gpu_exporter#30]
hey, sorry for bombarding you with issues)

could you give an advice on how to add node name to the dashboard for multinode setups?
currently it's identified by GPU UUID, we have a lot of nodes in our cluster and knowing UUIDs of all nodes GPUs is a bit impractical, so i would like to extend the grafana dashboard, and, ideally, have something like this
![image](https://user-images.githubusercontent.com/15367507/131976637-d5a52152-271c-49f6-bad5-113edaec37e7.png)

that would switch to correct nodename when you switch by GPU UUID in the top left dropdown.

it seems that it could be possible to derive node name combining Prometheus queries, grabbing ip from instance in **nvidia_smi_gpu_info** and somehow filtering results of **kube_pod_info{pod=~"ozdemir-nvidia-gpu-expo.*"}** on host_ip, from where node name is available.
![image](https://user-images.githubusercontent.com/15367507/131977686-5986e91d-fb3a-40f1-939a-d70008de5539.png)

but not sure, if that's possible.
i will continue to dig into prometheus queries, would appreciate any advice on that!

**Comment by ArtemAlagizov** [comment]
alright, i have a solution, need to improve it a bit, but it will do, i think:

![image](https://user-images.githubusercontent.com/15367507/131993927-e13dd972-26e7-4b6c-b35f-82fd6e74ba3f.png)

----

the way i did it:
i added a couple of Grafana variables to the dashboard, with filtering and extracting resulting values.
* one to fetch node ip from instance
![image](https://user-images.githubusercontent.com/15367507/131992199-88ff2635-2e4a-46c2-8b2f-883a25d77dba.png)
  ```bash
  # query
  nvidia_smi_gpu_info{uuid=~"$gpu"}
  # regex
  /.*instance="(.*):.*".*/
  ```

* one to get node name using node ip
![image](https://user-images.githubusercontent.com/15367507/131992410-2e55b08b-9c52-4d3d-b248-537d384c0f4b.png)
  ```bash
  # query
  kube_pod_info{pod=~"ozdemir-nvidia-gpu-expo.*", host_ip=~"$node_ip"}
  # regex
  /.*node="(.*)",pod=.*/
  ```

the second variable regex might be not robust enough, as i need to check that it is always followed by "pod=", or adjust the regex to cut everything after the quotes.


overall, i presume it works with enabled hostPort, otherwise filtering will need to be done on pod_ip.

here is templating section of JSON for updated dashboard
```json
 "templating": {
    "list": [
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_PROMETHEUS}",
        "definition": "label_values(nvidia_smi_index, uuid)",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": "GPU",
        "multi": false,
        "name": "gpu",
        "options": [],
        "query": {
          "query": "label_values(nvidia_smi_index, uuid)",
          "refId": "StandardVariableQuery"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
	  {
        "allValue": null,
        "current": {},
        "datasource": null,
        "definition": "nvidia_smi_gpu_info{uuid=~\"$gpu\"}",
        "description": null,
        "error": null,
        "hide": 2,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "node_ip",
        "options": [],
        "query": {
          "query": "nvidia_smi_gpu_info{uuid=~\"$gpu\"}",
          "refId": "StandardVariableQuery"
        },
        "refresh": 1,
        "regex": "/.*instance=\"(.*):.*\".*/",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      },
      {
        "allValue": null,
        "current": {},
        "datasource": null,
        "definition": "kube_pod_info{pod=~\"ozdemir-nvidia-gpu-expo.*\", host_ip=~\"$node_ip\"}",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "node_name",
        "options": [],
        "query": {
          "query": "kube_pod_info{pod=~\"ozdemir-nvidia-gpu-expo.*\", host_ip=~\"$node_ip\"}",
          "refId": "StandardVariableQuery"
        },
        "refresh": 1,
        "regex": "/.*node=\"(.*)\",pod=.*/",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  }
```

**Comment by utkuozdemir** [comment]
> hey, sorry for bombarding you with issues)
no worries, pls keep them coming so I can improve

I think your approach of forking/modifying the dashboard is correct. The exporter itself is designed to run everywhere, not necessarily on Kubernetes. So it is agnostic to the nodes etc.

You can not only edit the dashboard, bu also can use the metric relabeling config options of Prometheus to "attach" any additional labels you want from Kubernetes. With those in hand you can get the job done 🙂
