### ISSUE TITLE
No metrics for multiple master nodes

### ISSUE THREAD

**Issue by ArtemAlagizov** [utkuozdemir/nvidia_gpu_exporter#32]
Hey man, me again!

Having another issue, may be you could help.
I have same setup as before, but now more master nodes: 3 master nodes and 2 worker nodes.
The issue is that prometheus does not seem to have access to the metrics from the 2 new master nodes for some reason.
And consecutively, they are not displayed in the grafana dashboard.  
All nodes have nvidia_gpu_exporter running.

![image](https://user-images.githubusercontent.com/15367507/132493826-337c8b25-4a4d-4c5d-ae04-c0ca06b0bf61.png)

![image](https://user-images.githubusercontent.com/15367507/132493665-e4b33eae-b0ce-4b64-8c7e-2a5493c375b3.png)

![image](https://user-images.githubusercontent.com/15367507/132494599-63f1ff5d-0fa2-4bd0-ac40-aac814f59177.png)

that's how i deploy nvidia_gpu_exporter
```bash
helm install --version=0.3.1 ozdemir utkuozdemir/nvidia-gpu-exporter -f nvidia-gpu-ozdemir-values.yml
```

with such values
```bash
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
    operator: Exists

hostPort:
  enabled: true
  port: 31585
```

Might be missing something obvious, will continue the investigation.

**Comment by utkuozdemir** [comment]
Hey! 👋 
Just to make sure - did you update your prometheus targets?

**Comment by ArtemAlagizov** [comment]
ah, yes, you are right!
didn't properly wake up yet today)
everything works now, thanks!

**Comment by utkuozdemir** [comment]
No problem :)

My recommendation is to use the `ServiceMonitor` inside the chart instead of manually updating the targets every time. It will be less error-prone.

For that you will need to use prometheus-operator (I use this: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack)

**Comment by ArtemAlagizov** [comment]
ah, cool, thanks!
i do use prometheus operator, but currently my ansible playbook dynamically constructs a string with targets and appends it to the prometheus-operator-values.yml file before deploying prometheus-operator chart)
your solution sounds more elegant for sure
