### ISSUE TITLE
Add metric to get `nvidia-smi` command's exit status that it is error or success

### ISSUE THREAD

**Issue by lakinduakash** [utkuozdemir/nvidia_gpu_exporter#63]
In some environments `nvidia-smi` commands returns with error code. 

Ex:
```
$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
```
 Can you add simple metric (ie: `nvidia_smi_command_status`) to get whether `nvidia-smi` commands run successfully.

I think we need to add new metric  if there is `stderr`

```go
cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := runCmd(cmd)
	if err != nil {
		return nil, fmt.Errorf("command failed. stderr: %s err: %w", stderr.String(), err)
	}

	t, err := parseCSVIntoTable(strings.TrimSpace(stdout.String()), qFields)
	if err != nil {
		return nil, err
	}

	return &t, nil
```

Thanks

**Comment by utkuozdemir** [comment]
I just checked it quickly:
```bash
nvidia-smi --query-gpu="timestamp,nonexistent" --format=csv 2>stderr.log 1>stdout.log
```

and it seems `nvidia-smi` writes to stdout even the error output. So stderr wouldn't help here. But it returns properly a non-zero exit code. So I can simply expose the return code in an additional metric, no problem.

Can you check if the error you get returns a non-zero exit code as well?

Thanks

**Comment by utkuozdemir** [comment]
Also, there is the `nvidia_smi_failed_scrapes_total` that is incremented on every time the command is failed, if that helps you.

**Comment by lakinduakash** [comment]
In my case it returns non-zero exit code. So i think metric to expose non-zero exit code would suffice. Thanks for the fast reply.

**Comment by lakinduakash** [comment]
This returns 

> Also, there is the `nvidia_smi_failed_scrapes_total` that is incremented on every time the command is failed, if that helps you.

Does it reset when command goes okay?

**Comment by lakinduakash** [comment]
Actually I want to write alert rule (with prometheus) to trigger if and gpu error with `nvidia-smi`.

**Comment by utkuozdemir** [comment]
No, it's a counter, only goes up. I can add the return code, no problem.

**Comment by lakinduakash** [comment]
> No, it's a counter, only goes up. I can add the return code, no problem.

Yes, please. I think separate metric will do the thing. Thanks in advance.

**Comment by utkuozdemir** [comment]
Added it on https://github.com/utkuozdemir/nvidia_gpu_exporter/commit/2d21940d130a9e7db76fbeeab77abbd2305b6ce7

The gauge name is `nvidia_smi_command_exit_code`

Please give it a try and see if it helps :)

**Comment by lakinduakash** [comment]
Thanks for the quick implementation. I'll check that. 🙂

**Comment by lakinduakash** [comment]
It works like charm.
