### ISSUE TITLE
got errors "couldn't parse number from: [n/a]"

### ISSUE THREAD

**Issue by kiroswu** [utkuozdemir/nvidia_gpu_exporter#68]
**Describe the bug**
executed command: # ./nvidia_gpu_exporter --web.listen-address :20127 --nvidia-smi-command="nvidia-smi" --log.level=debug
refresh nvidia-gpu-metrics dashboard in Grafana, then command console throws errors and dashboard shows nothing

**To Reproduce**
1. Run command './nvidia_gpu_exporter --web.listen-address :20127 --nvidia-smi-command="nvidia-smi" --log.level=debug'
2. See error
![image](https://user-images.githubusercontent.com/19584792/161932184-098ec92a-ab38-4be1-8819-e98fcc388d7b.png)
![image](https://user-images.githubusercontent.com/19584792/161932253-72f7d49a-39c1-42bd-97c4-ba6fdef951c1.png)

**Expected behavior**
dashboard shows metrics data normally

**Model and Version**
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |

 - GPU Model [e.g. `GeForce RTX 2080 TI`]
 - App version and architecture [' linux_x86_64']
 - Operating System [e.g. `Ubuntu 18.04`]
 - Nvidia GPU driver version [e.g. `Linux driver nvidia-driver-450`]
 
root@4d15723e44d8:/home# ./nvidia_gpu_exporter --version
nvidia_gpu_exporter, version 0.4.0 (branch: HEAD, revision: 76d7496285a4c5f36a4520eaa3fe32fb0c400992)
  build user:       goreleaser
  build date:       2022-02-08T00:42:44Z
  go version:       go1.17.5
  platform:         linux/amd64

could you give a suggestion? Thx!

**Comment by utkuozdemir** [comment]
Can you please run the following command and share the output here:
```
nvidia-smi --query-gpu="timestamp,driver_version,count,name,serial,uuid,pci.bus_id,pci.domain,pci.bus,pci.device,pci.device_id,pci.sub_device_id,pcie.link.gen.current,pcie.link.gen.max,pcie.link.width.current,pcie.link.width.max,index,display_mode,display_active,persistence_mode,accounting.mode,accounting.buffer_size,driver_model.current,driver_model.pending,vbios_version,inforom.img,inforom.oem,inforom.ecc,inforom.pwr,gom.current,gom.pending,fan.speed,pstate,clocks_throttle_reasons.supported,clocks_throttle_reasons.active,clocks_throttle_reasons.gpu_idle,clocks_throttle_reasons.applications_clocks_setting,clocks_throttle_reasons.sw_power_cap,clocks_throttle_reasons.hw_slowdown,clocks_throttle_reasons.hw_thermal_slowdown,clocks_throttle_reasons.hw_power_brake_slowdown,clocks_throttle_reasons.sw_thermal_slowdown,clocks_throttle_reasons.sync_boost,memory.total,memory.used,memory.free,compute_mode,utilization.gpu,utilization.memory,encoder.stats.sessionCount,encoder.stats.averageFps,encoder.stats.averageLatency,ecc.mode.current,ecc.mode.pending,ecc.errors.corrected.volatile.device_memory,ecc.errors.corrected.volatile.dram,ecc.errors.corrected.volatile.register_file,ecc.errors.corrected.volatile.l1_cache,ecc.errors.corrected.volatile.l2_cache,ecc.errors.corrected.volatile.texture_memory,ecc.errors.corrected.volatile.cbu,ecc.errors.corrected.volatile.sram,ecc.errors.corrected.volatile.total,ecc.errors.corrected.aggregate.device_memory,ecc.errors.corrected.aggregate.dram,ecc.errors.corrected.aggregate.register_file,ecc.errors.corrected.aggregate.l1_cache,ecc.errors.corrected.aggregate.l2_cache,ecc.errors.corrected.aggregate.texture_memory,ecc.errors.corrected.aggregate.cbu,ecc.errors.corrected.aggregate.sram,ecc.errors.corrected.aggregate.total,ecc.errors.uncorrected.volatile.device_memory,ecc.errors.uncorrected.volatile.dram,ecc.errors.uncorrected.volatile.register_file,ecc.errors.uncorrected.volatile.l1_cache,ecc.errors.uncorrected.volatile.l2_cache,ecc.errors.uncorrected.volatile.texture_memory,ecc.errors.uncorrected.volatile.cbu,ecc.errors.uncorrected.volatile.sram,ecc.errors.uncorrected.volatile.total,ecc.errors.uncorrected.aggregate.device_memory,ecc.errors.uncorrected.aggregate.dram,ecc.errors.uncorrected.aggregate.register_file,ecc.errors.uncorrected.aggregate.l1_cache,ecc.errors.uncorrected.aggregate.l2_cache,ecc.errors.uncorrected.aggregate.texture_memory,ecc.errors.uncorrected.aggregate.cbu,ecc.errors.uncorrected.aggregate.sram,ecc.errors.uncorrected.aggregate.total,retired_pages.single_bit_ecc.count,retired_pages.double_bit.count,retired_pages.pending,temperature.gpu,temperature.memory,power.management,power.draw,power.limit,enforced.power.limit,power.default_limit,power.min_limit,power.max_limit,clocks.current.graphics,clocks.current.sm,clocks.current.memory,clocks.current.video,clocks.applications.graphics,clocks.applications.memory,clocks.default_applications.graphics,clocks.default_applications.memory,clocks.max.graphics,clocks.max.sm,clocks.max.memory,mig.mode.current,mig.mode.pending" --format=csv
```

Also, please when the exporter is running, hit the endpoint `http://localhost:9835/metrics` in your browser and share the output here?

**Comment by utkuozdemir** [comment]
The errors saying "couldn't parse number from..." are debug level logs and are expected, you don't need to be worried about them. Only logs with `level=error` are significant.

**Comment by utkuozdemir** [comment]
Thanks. I have just released `v0.5.0` with more helpful logs, can you install it and publish the logs output here?

28 seconds is definitely not normal but not sure if it is related to the exporter. Please give it a try with `127.0.0.1` instead of localhost: `http://127.0.0.1:9835/metrics`.

**Comment by kiroswu** [comment]
Tried again using v0.5.0, same issue. Actually I request url via real_ip remotely, not 127 or localhost
Logs as attachment files:
[command_log.txt](https://github.com/utkuozdemir/nvidia_gpu_exporter/files/8438856/command_log.txt)
[entpoint_response.txt](https://github.com/utkuozdemir/nvidia_gpu_exporter/files/8438860/entpoint_response.txt)

 The request cost 1min using v0.5.0:
![image](https://user-images.githubusercontent.com/19584792/162100521-7fffdf19-cc1d-4f18-ba24-40448d2e9bd6.png)

**Comment by utkuozdemir** [comment]
0.5.0 is not supposed to fix the issue, it doesn't contain any fixes.
It should just log the error in more detail. Can you check the error logs and post them here please?

**Comment by kiroswu** [comment]
> Tried again using v0.5.0, same issue. Actually I request url via real_ip remotely, not 127 or localhost Logs as attachment files: [command_log.txt](https://github.com/utkuozdemir/nvidia_gpu_exporter/files/8438856/command_log.txt) [entpoint_response.txt](https://github.com/utkuozdemir/nvidia_gpu_exporter/files/8438860/entpoint_response.txt)
> 
> The request cost 1min using v0.5.0: ![image](https://user-images.githubusercontent.com/19584792/162100521-7fffdf19-cc1d-4f18-ba24-40448d2e9bd6.png)

See the log file command_log.txt, seems it same with previous v0.4.0.

**Comment by utkuozdemir** [comment]
Ah ok I didn't see the attached documents.

Actually logs look ok and endpoint response has actual data in it. - See the power draw and temperature for example:
```
nvidia_smi_power_draw_watts{uuid="0e01d9aa-96e8-e62d-bc23-cd9d08891bef"} 54.01
nvidia_smi_power_draw_watts{uuid="2227faca-c5d5-a1a1-7791-e66e8514a41b"} 67.51
...
nvidia_smi_temperature_gpu{uuid="0e01d9aa-96e8-e62d-bc23-cd9d08891bef"} 43
nvidia_smi_temperature_gpu{uuid="2227faca-c5d5-a1a1-7791-e66e8514a41b"} 42
...
```

This means the exporter is working correctly and the misconfiguration is somewhere on the Prometheus scraping or on Grafana->Prometheus connection.

Can you go to prometheus UI and see if metrics are scraped?
Also go to settings and check the data sources and please verify that Prometheus data source is accessible.

I suspect that prometheus scraping fails because scrape takes too long, and by default `scrape_timeout` is 10 seconds. Maybe you try increasing this timeout to a big number (5m), restart prometheus and see if it can scrape afterwards? See `scrape_timeout` here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

**Comment by kiroswu** [comment]
Thx a lot. It's OK now after modified the scrape_timeout. 
Currently confused on if scraping more than 10 nodes & 4 pieces GPU in every node at one time, dashboard would be unavaliable for timeout. How to resolved it? doesn't make sense to enlarge scrape_timeout * 10

BTW. How can i implement summary table like id 11074 ? https://grafana.com/grafana/dashboards/11074 
![image](https://user-images.githubusercontent.com/19584792/162168105-1b0a5bdd-716d-4055-ac36-2a2a1c5e2f07.png)

**Comment by utkuozdemir** [comment]
Scraping taking that long is still not normal, I would suspect a single node/single GPU having some sort of issue and therefore delaying the response, but we cannot know for sure. It needs deeper investigation from your side.

One tip: you can check if you are giving enough compute resources/memory to the exporter, prometheus and grafana. You can increase their resources and give it a try.

About the table, I am not a Grafana expert. What I would suggest is downloading that dashboard and having a look how they did it and maybe adapt it to my dashboard (contributions welcome 🙂).

**Comment by kiroswu** [comment]
Thx a lot. I will try it for dashboard change.
Also expect exporter performance optimization for mutli-nodes and dashboard upgrade.
Great project!
