### ISSUE TITLE
Tutorial for Grafana setup?

### ISSUE THREAD

**Issue by eM-Krow** [utkuozdemir/nvidia_gpu_exporter#7]
Can't seem to figure out how to get it properly setup with Grafana no matter what I do.

**Comment by utkuozdemir** [comment]
I plan to provide a single powershell script to install the whole stack.

**Comment by utkuozdemir** [comment]
Please have a look into the new all-in-one installation method to see if it fits your needs: https://github.com/utkuozdemir/nvidia_gpu_exporter/blob/master/INSTALL.md#all-in-one-windows-installation

**Comment by eM-Krow** [comment]
Doesn't seem to work for me. I rand the PS1 in admin, got a failed to start service error, so I removed the service with NSSM, followed the create a service instructions again, got the service again, ran the PS1 again, no errors, redid the grafana import and selected prometheus, was blank info in grafana.

**Comment by utkuozdemir** [comment]
Can you please verify if you have metrics in prometheus at all? Just type few letters of `nvidia_smi` to the prometheus query field on localhost:9090, and it should auto-complete. Would look like this:
 
![image](https://user-images.githubusercontent.com/1465819/125698688-30464a39-dccd-4f33-ad87-f1f483699401.png)

**Comment by eM-Krow** [comment]
Doesn't show up for me.

**Comment by utkuozdemir** [comment]
Let's see if the exporter is working properly. Can you hit http://localhost:9835/metrics and share the output here?

**Comment by eM-Krow** [comment]
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0.0005046
go_gc_duration_seconds_sum 0.0005076
go_gc_duration_seconds_count 17
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 8
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.16.5"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 6.978784e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 5.8075816e+07
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.452263e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 164230
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 7.352912505227636e-07
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 3.46804e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 6.978784e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 7.544832e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 8.085504e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 12067
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 5.57056e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 1.5630336e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6263011708653896e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 176297
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 37376
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 49152
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 208216
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 212992
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 1.1609808e+07
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 2.451273e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.14688e+06
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.14688e+06
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 2.4410936e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 20
# HELP nvidia_gpu_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which nvidia_gpu_exporter was built.
# TYPE nvidia_gpu_exporter_build_info gauge
nvidia_gpu_exporter_build_info{branch="HEAD",goversion="go1.16.5",revision="c30b2db58ebfb10f1a98e9da159095b824230b47",version="0.2.0"} 1
# HELP nvidia_smi_failed_scrapes_total Number of failed scrapes
# TYPE nvidia_smi_failed_scrapes_total counter
nvidia_smi_failed_scrapes_total 115
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.640625
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.6777216e+07
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 176
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.304e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.626299574e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.9569024e+07
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 114
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0

**Comment by utkuozdemir** [comment]
I see, the problem is with the exporter, the `nvidia_smi_` metrics are not collected and exported for some reason. Can you please run in a cmd or powershell prompt this command:
```
nvidia-smi --query-gpu="uuid,name,driver_model.current,driver_model.pending,vbios_version,fan.speed,memory.used" --format=csv
```
And share its output?

**Comment by eM-Krow** [comment]
Ignore the usage%, mining eth when I don't game Lol: 
![image](https://user-images.githubusercontent.com/87371945/125701552-f036888c-c131-449e-9b35-aa5d80d747aa.png)

**Comment by utkuozdemir** [comment]
Ok, it is working properly as expected 🤔 

Just wondering, don't you have the `nvidia-smi.exe` binary located in `C:\Windows\system32\nvidia-smi.exe`?
In the default configuration, the exporter expects nvidia-smi binary to be accessible from anywhere (it should be in `PATH`).

In a regular installation of drivers, it is located under system32. But in your screenshot I see that you had to go into NVSMI dir to run it. 

Can you check that? Also, are you using some custom drivers?

If you can verify that it is NOT in the PATH, then you'll need to add that `c:\program files\nvidia corporation\nvsmi` to your PATH. Then you can restart the `nvidia_smi_exporter` service (`Restart-Service -Name nvidia_smi_exporter` in PS) and try again.

**Comment by eM-Krow** [comment]
I'm using NVIDIA's Standard drivers due to being on Windows 10 Ameliorated. So I guess it never installed it to that location?

**Comment by utkuozdemir** [comment]
Ok, that can explain the issue. Please try the PATH thing - it should work.

**Comment by eM-Krow** [comment]
Okay so now, Prometheus now shows some info: 
![image](https://user-images.githubusercontent.com/87371945/125703053-28d2a36b-d8ef-4814-b0d7-db9b9c6241f5.png)

**Comment by eM-Krow** [comment]
It's all working now. Appreciate it!: 
![image](https://user-images.githubusercontent.com/87371945/125703503-cf51c366-26c0-4315-b32b-95051f2c4553.png)

**Comment by utkuozdemir** [comment]
Beautiful 😍 Enjoy!
