### ISSUE TITLE
Core/Mem Clock Speed (MHz) and Memory Junction Temp Displays?

### ISSUE THREAD

**Issue by eM-Krow** [utkuozdemir/nvidia_gpu_exporter#8]
Eg maybe have an extra bit of info about the clock speeds in MHz and the memory junction temperatures if possible? I'd suggest the MHz be placed next to the respective utilization percentages and the temperature have the memory temp under the core temp.

Not sure how doable that is in NVIDIA SMI but would be a neat addition.

Wait nevermind I'm dumb and didn't see the bottom lol. Still mem temp would be nice.

**Comment by utkuozdemir** [comment]
It seems the memory junction temperature is not provided by the `nvidia-smi` tool, and getting it in some other way would beat the purpose of the project, which is being cross-platform and only depending on the nvidia-smi interface/contract.

About the clock speeds, gauges can be added to show it at that instant, but I think the bottom row is doing ok so far (as you noticed) :)

If you have any other suggestions, please feel free to open another ticket.
