### ISSUE TITLE
Running nvidia-smi multiple time is causing to hanging for GPU

### ISSUE THREAD

**Issue by eypklyc** [utkuozdemir/nvidia_gpu_exporter#89]
Hello, Thank you for the great work. 

First of all this not a bug report! It's related with Nvidia drivers and I'm just informing.. The story is,
We are using tool for a while. After last nvidia update unfortunately we are facing some troubles. No problem with the newer GPU's but the old ones hanging after calling nvidia-smi. Is anyone faced this weird problem in these days?

GPU: RTX Titan, driver version 450.80.02 and kernel is modules/5.4.0-124-generic

**Comment by utkuozdemir** [comment]
Hi, thank you for using the tool and for the information.

I haven't heard about this issue until now. I'll keep this issue open for a while so that it has some visibility. In the meantime, if you have new findings, they are the most welcome.

**Comment by utkuozdemir** [comment]
I think it is time to close this one. Feel free to share if you have some findings.

**Comment by eypklyc** [comment]
Hi again Utku. After I while I back to suggest one thing. I relalized not matter what the linux kernel is provided nvidia driver causing some hanging on GPU if we call nvidia-smi multiple times in a minute. So I'm wondering maybe we can add option to set the scrape interval here. From my observation x4 Titan RTX with driver 525 and  RTX  3090 with driver 530 causing the problem. Also realized that a5000 is okay with 525 from my testings. 

If anyone wants to simulate the issue, do this, while running an training on GPU try to run nvidia-smi with watch command.

**Comment by utkuozdemir** [comment]
Hi, the exporter itself does not do any nvidia-smi calls by itself. Scraping is done externally - you can configure it on prometheus side. At each request to /metrics (a scrape), nvidia-smi will be called.

**Comment by eypklyc** [comment]
That's great, I'll set related opiton on prometheus side, if it solve the issue I'll update the issue again. Thank you so much Utku

**Comment by utkuozdemir** [comment]
The real fix here is to stop running `nvidia-smi` on every scrape. Tracked now in #405.
