### ISSUE TITLE
Prometheus setup problems

### ISSUE THREAD

**Issue by catid** [utkuozdemir/nvidia_gpu_exporter#91]
![image](https://user-images.githubusercontent.com/252193/187814775-5c239908-349a-4993-8ee4-49edad4f83d7.png)

Here's what I'm seeing while trying to configure the Data Source:

```
Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html lang=|..., bigger context ...|<html lang="en"> <head><title>Nvidia GPU Exporter</|...
```

I think I followed the install guide correctly but still something is not set up properly somewhere...

**Comment by utkuozdemir** [comment]
Oh I see, there's a misunderstanding. You need to set up a prometheus which is configured to scrape this exporter's endpoint, and Grafana should point to that Prometheus as the data source. Needs to be `Grafana->Prometheus->Exporter`. This won't work: `Grafana->Exporter`.

**Comment by catid** [comment]
Ah okay thanks!
