### ISSUE TITLE
Error starting HTTP server

### ISSUE THREAD

**Issue by fopearcano** [utkuozdemir/nvidia_gpu_exporter#92]
Hi. I get this error as I'm trying to connect to Grafana

ts=2022-09-15T10:57:07.347Z caller=main.go:84 level=info msg="Listening on address" address=:9835
ts=2022-09-15T10:57:07.348Z caller=main.go:99 level=error msg="Error starting HTTP server" err="listen tcp :9835: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."

What can I do?

Can you also show an example of the --web.config.file ?

Thanks

**Comment by utkuozdemir** [comment]
Hi, on which port you are running Grafana on? This exporter by default listens to TCP port 9835, and there must be no other process that is listening to that port. According to the error you sharedd, there is another process already listening on that port.
