### ISSUE TITLE
Can't visualize metrics on Grafana Dashboard

### ISSUE THREAD

**Issue by mbenencase** [utkuozdemir/nvidia_gpu_exporter#95]
Hey, currently I'm facing a problem that I can't visualize the metrics on my Grafana Dashboard. I'll describe the steps that I followed

1. I installed the .deb package according to what is described in INSTALL.md. My laptop has Ubuntu 20.04 and my GPU is a GeForce 3060.
2. On CONFIGURE.md I set the command of `nvidia-smi` as
```
nvidia_gpu_exporter --nvidia-smi-command 'nvidia-smi'
```
3. I imported the dashboard that is ready-to-use on Grafana, but no metrics appeared.

After step (3), I was looking in this GitHub for similar issues and I found this one: #7 . However, one of the suggestions is to verify the metrics log on Prometheus on http://localhost:9090, but this page throws me the `404 Error Page not Found`. So I believe that there's a Prometheus setup step that I'm missing. And that's what I think it's my problem.

How could I setup Prometheus properly to be able to visualize the metrics on the Dashboard?

**Comment by utkuozdemir** [comment]
Hi,

You do not need to pass `--nvidia-smi-command nvidia-smi` since it is the default value anyway - the flag is only for the cases when you want to override it.

The problem indeed seems like related to your Prometheus setup. Are you running on Windows?

**Comment by utkuozdemir** [comment]
Cool, how did you install prometheus? Is it installed as a systemd service?

You can check its logs using `journalctl -xeu prometheus` (replace with the service name it is installed, if it is not `prometheus`).

Your first goal must be to get `http://localhost:9090` working and seeing some metrics there. You need to troubleshoot your Prometheus installation. Only then this exporter becomes relevant.

**Comment by mbenencase** [comment]
@utkuozdemir I think that my problem is that I didn't install it. I'll verify how to install it properly.

**Comment by utkuozdemir** [comment]
Closing this issue, as it is not related to the exporter itself.
