### ISSUE TITLE
how to make docker images

### ISSUE THREAD

**Issue by yangyin2016** [utkuozdemir/nvidia_gpu_exporter#96]
hello， I want to use this project to make docker images，but I failed，can you tell me how to make docker images?

**Comment by utkuozdemir** [comment]
Hi,

I provide the prebuilt docker images here: https://hub.docker.com/repository/docker/utkuozdemir/nvidia_gpu_exporter

They are based on [this Dockerfile in the repository](https://github.com/utkuozdemir/nvidia_gpu_exporter/blob/master/Dockerfile).

You can use it directly or extend from it using
```Dockerfile
FROM utkuozdemir/nvidia_gpu_exporter:1.2.0

# your customizations
```

I hope this helps you to achieve what you need.
