### ISSUE TITLE
Add option to specify IPv4

### ISSUE THREAD

**Issue by Operating3336** [utkuozdemir/nvidia_gpu_exporter#99]
Hi,

I've been using your software, and it works great, but I noticed that there doesn't seem to be an option to specify IPv4. I would like to request that you add an option to allow users to specify IPv4 only.

I tried with `--web.listen-address=0.0.0.0:9835` but still using ipv6.

This feature would be particularly useful for those of us who are running the software on systems that have both IPv4 and IPv6 enabled, and need to ensure that the software is using IPv4 only.

I understand that this may not be a high priority feature, but I believe that it would greatly enhance the functionality of your software for users like myself.

Thank you for your consideration.

**Comment by utkuozdemir** [comment]
I just implemented it and made a new release. You can achieve this now by passing `--web.network=tcp4` on command line.

**Comment by Operating3336** [comment]
Thanks, @utkuozdemir !
